{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 8, "minor": 5, "revision": 0, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [ 100.0, 100.0, 640.0, 480.0 ],
		"bglocked": 0,
		"openinpresentation": 0,
		"default_fontsize": 12.0,
		"default_fontface": 0,
		"default_fontname": "Arial",
		"gridonopen": 1,
		"gridsize": [ 15.0, 15.0 ],
		"gridsnaponopen": 1,
		"objectsnaponopen": 1,
		"statusbarvisible": 2,
		"toolbarvisible": 1,
		"boxes": [
			{ "box": { "id": "in1", "maxclass": "newobj", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 30.0, 20.0, 32.0, 22.0 ], "text": "in 1", "comment": "midinote: midi vel durMs" } },
			{ "box": { "id": "unpack", "maxclass": "newobj", "numinlets": 1, "numoutlets": 3, "outlettype": [ "float", "float", "float" ], "patching_rect": [ 30.0, 60.0, 100.0, 22.0 ], "text": "unpack 0. 0. 0." } },
			{ "box": { "id": "octshift", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 30.0, 95.0, 60.0, 22.0 ], "text": "+ #2" } },
			{ "box": { "id": "mtof", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 30.0, 130.0, 40.0, 22.0 ], "text": "mtof" } },
			{ "box": { "id": "oscsel", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 170.0, 70.0, 22.0 ], "text": "#1~ 440" } },
			{ "box": { "id": "velscale", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 160.0, 95.0, 70.0, 22.0 ], "text": "/ 127." } },
			{ "box": { "id": "velamp", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 160.0, 125.0, 70.0, 22.0 ], "text": "* 0.35" } },
			{ "box": { "id": "addrel", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 240.0, 125.0, 60.0, 22.0 ], "text": "+ #3" } },
			{ "box": { "id": "envmsg", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 160.0, 160.0, 90.0, 22.0 ], "text": "pak 0. 0." } },
			{ "box": { "id": "envfmt", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 160.0, 195.0, 110.0, 22.0 ], "text": "$1 5, 0. $2" } },
			{ "box": { "id": "line", "maxclass": "newobj", "numinlets": 2, "numoutlets": 2, "outlettype": [ "signal", "bang" ], "patching_rect": [ 160.0, 262.0, 45.0, 22.0 ], "text": "line~" } },
			{ "box": { "id": "mult", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 300.0, 35.0, 22.0 ], "text": "*~" } },
			{ "box": { "id": "busy", "maxclass": "newobj", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 300.0, 262.0, 70.0, 22.0 ], "text": "thispoly~" } },
			{ "box": { "id": "freemsg", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 380.0, 228.0, 60.0, 22.0 ], "text": "mute 1 1" } },
			{ "box": { "id": "unmute", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 300.0, 195.0, 60.0, 22.0 ], "text": "mute 0" } },
			{ "box": { "id": "out1", "maxclass": "newobj", "numinlets": 1, "numoutlets": 0, "outlettype": [], "patching_rect": [ 30.0, 345.0, 50.0, 22.0 ], "text": "out~ 1" } }
		],
		"lines": [
			{ "patchline": { "source": [ "in1", 0 ], "destination": [ "unpack", 0 ] } },
			{ "patchline": { "source": [ "unpack", 0 ], "destination": [ "octshift", 0 ] } },
			{ "patchline": { "source": [ "octshift", 0 ], "destination": [ "mtof", 0 ] } },
			{ "patchline": { "source": [ "mtof", 0 ], "destination": [ "oscsel", 0 ] } },
			{ "patchline": { "source": [ "unpack", 1 ], "destination": [ "velscale", 0 ] } },
			{ "patchline": { "source": [ "velscale", 0 ], "destination": [ "velamp", 0 ] } },
			{ "patchline": { "source": [ "velamp", 0 ], "destination": [ "envmsg", 0 ] } },
			{ "patchline": { "source": [ "unpack", 2 ], "destination": [ "addrel", 0 ] } },
			{ "patchline": { "source": [ "addrel", 0 ], "destination": [ "envmsg", 1 ] } },
			{ "patchline": { "source": [ "envmsg", 0 ], "destination": [ "envfmt", 0 ] } },
			{ "patchline": { "source": [ "envfmt", 0 ], "destination": [ "line", 0 ] } },
			{ "patchline": { "source": [ "envfmt", 0 ], "destination": [ "unmute", 0 ] } },
			{ "patchline": { "source": [ "unmute", 0 ], "destination": [ "busy", 0 ] } },
			{ "patchline": { "source": [ "line", 1 ], "destination": [ "freemsg", 0 ] } },
			{ "patchline": { "source": [ "freemsg", 0 ], "destination": [ "busy", 0 ] } },
			{ "patchline": { "source": [ "oscsel", 0 ], "destination": [ "mult", 0 ] } },
			{ "patchline": { "source": [ "line", 0 ], "destination": [ "mult", 1 ] } },
			{ "patchline": { "source": [ "mult", 0 ], "destination": [ "out1", 0 ] } }
		]
	}
}
